title: Zajęcia 24 lutego
description: Wzorcowy projekt utworzony 24 lutego
theme: just-the-docs

url: https://lukaszpilat93/justthedocs-manual.github.io

aux_links:
  Template Repository: https://github.com/lukaszpilat93/justthedocs-manual/edit/main/_config.yml
